# ---------------------------------------------------
# Package: emlog (universell, mit schönen Anzeigenamen)
# Datei: config/packages/emlog.yaml
#
# Features:
# - Host/IP + Meterindex als Helper (UI änderbar)
# - REST URLs via resource_template
# - Brennwert/Zustandszahl + Preis/Grundpreis als Helper
# - Tarifwechsel ab Datum (aktuell/neu)
# - utility_meter für Tag/Monat/Jahr aus echten Zählerständen
# - Kosten Tag/Monat/Jahr inkl. Grundpreis
# ---------------------------------------------------

homeassistant:
  customize:
    # Utility Meter (Icons via customize)
    sensor.emlog_strom_verbrauch_tag_kwh_utility:
      icon: mdi:calendar-today
    sensor.emlog_strom_verbrauch_monat_kwh:
      icon: mdi:calendar-month
    sensor.emlog_strom_verbrauch_jahr_kwh:
      icon: mdi:calendar
    sensor.emlog_gas_verbrauch_tag_kwh_utility:
      icon: mdi:calendar-today
    sensor.emlog_gas_verbrauch_monat_kwh:
      icon: mdi:calendar-month
    sensor.emlog_gas_verbrauch_jahr_kwh:
      icon: mdi:calendar

input_text:
  emlog_host:
    name: 'Emlog Host/IP'
    icon: mdi:lan
    initial: '172.16.50.22'

input_number:
  emlog_strom_meterindex:
    name: 'Emlog Strom Meterindex'
    min: 1
    max: 3
    step: 1
    mode: box
    icon: mdi:counter
    initial: 1

  emlog_gas_meterindex:
    name: 'Emlog Gas Meterindex'
    min: 1
    max: 3
    step: 1
    mode: box
    icon: mdi:counter
    initial: 2

  emlog_gas_brennwert:
    name: 'Emlog Gas Brennwert'
    min: 0
    max: 20
    step: 0.001
    mode: box
    unit_of_measurement: 'kWh/m³'
    icon: mdi:fire
    initial: 11.58

  emlog_gas_zustandszahl:
    name: 'Emlog Gas Zustandszahl'
    min: 0
    max: 2
    step: 0.0001
    mode: box
    icon: mdi:gauge
    initial: 0.95

  # --- Strom Tarife (für Tarifwechsel) ---
  emlog_strom_preis_aktuell:
    name: 'Emlog Strom Arbeitspreis (aktuell)'
    min: 0
    max: 5
    step: 0.0001
    mode: box
    unit_of_measurement: 'EUR/kWh'
    icon: mdi:tag

  emlog_strom_preis_neu:
    name: 'Emlog Strom Arbeitspreis (neu)'
    min: 0
    max: 5
    step: 0.0001
    mode: box
    unit_of_measurement: 'EUR/kWh'
    icon: mdi:tag-outline

  emlog_strom_grundpreis_monat_aktuell:
    name: 'Emlog Strom Grundpreis pro Monat (aktuell)'
    min: 0
    max: 200
    step: 0.01
    mode: box
    unit_of_measurement: 'EUR/Monat'
    icon: mdi:calendar-month

  emlog_strom_grundpreis_monat_neu:
    name: 'Emlog Strom Grundpreis pro Monat (neu)'
    min: 0
    max: 200
    step: 0.01
    mode: box
    unit_of_measurement: 'EUR/Monat'
    icon: mdi:calendar-month-outline

  # --- Gas Tarife (für Tarifwechsel) ---
  emlog_gas_preis_aktuell:
    name: 'Emlog Gas Arbeitspreis (aktuell)'
    min: 0
    max: 5
    step: 0.0001
    mode: box
    unit_of_measurement: 'EUR/kWh'
    icon: mdi:tag

  emlog_gas_preis_neu:
    name: 'Emlog Gas Arbeitspreis (neu)'
    min: 0
    max: 5
    step: 0.0001
    mode: box
    unit_of_measurement: 'EUR/kWh'
    icon: mdi:tag-outline

  emlog_gas_grundpreis_monat_aktuell:
    name: 'Emlog Gas Grundpreis pro Monat (aktuell)'
    min: 0
    max: 200
    step: 0.01
    mode: box
    unit_of_measurement: 'EUR/Monat'
    icon: mdi:calendar-month

  emlog_gas_grundpreis_monat_neu:
    name: 'Emlog Gas Grundpreis pro Monat (neu)'
    min: 0
    max: 200
    step: 0.01
    mode: box
    unit_of_measurement: 'EUR/Monat'
    icon: mdi:calendar-month-outline

input_datetime:
  emlog_strom_tarifwechsel_ab:
    name: 'Emlog Strom Tarifwechsel ab'
    has_date: true
    has_time: false

  emlog_gas_tarifwechsel_ab:
    name: 'Emlog Gas Tarifwechsel ab'
    has_date: true
    has_time: false

rest:
  # ----------------------
  # Strom
  # ----------------------
  - resource_template: >
      http://{{ states('input_text.emlog_host') }}/pages/getinformation.php?export&meterindex={{ states('input_number.emlog_strom_meterindex') | int(1) }}
    timeout: 10
    scan_interval: 30
    sensor:
      - name: 'Emlog Produkt'
        unique_id: emlog_product
        icon: mdi:chip
        value_template: "{{ value_json.product | default('Emlog') }}"

      - name: 'Emlog Software Version'
        unique_id: emlog_software_version
        icon: mdi:information-outline
        value_template: '{{ value_json.version | float(0) }}'

      - name: 'Emlog Strom Zählerstand (kWh)'
        unique_id: emlog_strom_zaehlerstand_kwh
        icon: mdi:flash
        value_template: "{{ value_json['Zaehlerstand_Bezug']['Stand180'] | float(0) }}"
        unit_of_measurement: 'kWh'
        state_class: total_increasing
        device_class: energy

      - name: 'Emlog Strom Leistung (W)'
        unique_id: emlog_strom_wirkleistung_w
        icon: mdi:flash-outline
        value_template: "{{ value_json['Wirkleistung_Bezug']['Leistung170'] | float(0) }}"
        unit_of_measurement: 'W'
        state_class: measurement
        device_class: power

      - name: 'Emlog Strom Verbrauch heute (kWh)'
        unique_id: emlog_strom_verbrauch_tag_kwh
        icon: mdi:counter
        value_template: "{{ value_json['Kwh_Bezug']['Kwh180'] | float(0) }}"
        unit_of_measurement: 'kWh'
        state_class: total
        device_class: energy

      - name: 'Emlog Strom Betrag heute (EUR)'
        unique_id: emlog_strom_betrag_tag_eur
        icon: mdi:currency-eur
        value_template: "{{ value_json['Betrag_Bezug']['Betrag180'] | float(0) }}"
        unit_of_measurement: 'EUR'
        state_class: total
        device_class: monetary

  # ----------------------
  # Gas
  # ----------------------
  - resource_template: >
      http://{{ states('input_text.emlog_host') }}/pages/getinformation.php?export&meterindex={{ states('input_number.emlog_gas_meterindex') | int(2) }}
    timeout: 10
    scan_interval: 30
    sensor:
      - name: 'Emlog Gas Zählerstand (m³)'
        unique_id: emlog_gas_zaehlerstand_m3
        icon: mdi:gas-cylinder
        value_template: "{{ value_json['Zaehlerstand_Bezug']['Stand180'] | float(0) }}"
        unit_of_measurement: 'm³'
        state_class: total_increasing
        device_class: gas

      - name: 'Emlog Gas Leistung (W)'
        unique_id: emlog_gas_wirkleistung_w
        icon: mdi:fire
        value_template: "{{ value_json['Wirkleistung_Bezug']['Leistung170'] | float(0) }}"
        unit_of_measurement: 'W'
        state_class: measurement
        device_class: power

      - name: 'Emlog Gas Verbrauch heute (kWh)'
        unique_id: emlog_gas_verbrauch_tag_kwh
        icon: mdi:counter
        value_template: "{{ value_json['Kwh_Bezug']['Kwh180'] | float(0) }}"
        unit_of_measurement: 'kWh'
        state_class: total
        device_class: energy

      - name: 'Emlog Gas Betrag heute (EUR)'
        unique_id: emlog_gas_betrag_tag_eur
        icon: mdi:currency-eur
        value_template: "{{ value_json['Betrag_Bezug']['Betrag180'] | float(0) }}"
        unit_of_measurement: 'EUR'
        state_class: total
        device_class: monetary

utility_meter:
  # Strom: aus echtem Zählerstand (kWh)
  emlog_strom_verbrauch_tag_kwh_utility:
    unique_id: emlog_strom_verbrauch_tag_kwh_utility
    name: 'Emlog Strom Verbrauch Tag (Utility)'
    source: sensor.emlog_strom_zaehlerstand_kwh
    cycle: daily

  emlog_strom_verbrauch_monat_kwh:
    unique_id: emlog_strom_verbrauch_monat_kwh
    name: 'Emlog Strom Verbrauch Monat'
    source: sensor.emlog_strom_zaehlerstand_kwh
    cycle: monthly

  emlog_strom_verbrauch_jahr_kwh:
    unique_id: emlog_strom_verbrauch_jahr_kwh
    name: 'Emlog Strom Verbrauch Jahr'
    source: sensor.emlog_strom_zaehlerstand_kwh
    cycle: yearly

  # Gas: aus umgerechnetem kWh-Zählerstand (gesamt)
  emlog_gas_verbrauch_tag_kwh_utility:
    unique_id: emlog_gas_verbrauch_tag_kwh_utility
    name: 'Emlog Gas Verbrauch Tag (Utility)'
    source: sensor.emlog_gas_zaehlerstand_kwh
    cycle: daily

  emlog_gas_verbrauch_monat_kwh:
    unique_id: emlog_gas_verbrauch_monat_kwh
    name: 'Emlog Gas Verbrauch Monat'
    source: sensor.emlog_gas_zaehlerstand_kwh
    cycle: monthly

  emlog_gas_verbrauch_jahr_kwh:
    unique_id: emlog_gas_verbrauch_jahr_kwh
    name: 'Emlog Gas Verbrauch Jahr'
    source: sensor.emlog_gas_zaehlerstand_kwh
    cycle: yearly

template:
  - sensor:
      - name: 'Emlog Gas Umrechnungsfaktor (kWh pro m³)'
        unique_id: emlog_gas_umrechnungsfaktor_kwh_pro_m3
        icon: mdi:swap-horizontal
        unit_of_measurement: 'kWh/m³'
        state: >
          {{ (states('input_number.emlog_gas_brennwert') | float(11.58)) *
             (states('input_number.emlog_gas_zustandszahl') | float(0.95)) }}

      - name: 'Emlog Gas Zählerstand (kWh)'
        unique_id: emlog_gas_zaehlerstand_kwh
        icon: mdi:gas-burner
        unit_of_measurement: 'kWh'
        device_class: energy
        state_class: total_increasing
        availability: >
          {{ states('sensor.emlog_gas_zaehlerstand_m3') not in ['unknown','unavailable','none',''] }}
        state: >
          {% set m3 = states('sensor.emlog_gas_zaehlerstand_m3') | float(0) %}
          {% set bw = states('input_number.emlog_gas_brennwert') | float(11.58) %}
          {% set z  = states('input_number.emlog_gas_zustandszahl') | float(0.95) %}
          {{ (m3 * bw * z) | round(3) }}

      - name: 'Emlog Strom Arbeitspreis (effektiv)'
        unique_id: emlog_strom_preis_effektiv
        icon: mdi:tag
        unit_of_measurement: 'EUR/kWh'
        state: >
          {% set dt = states('input_datetime.emlog_strom_tarifwechsel_ab') %}
          {% set wechsel = as_datetime(dt) if dt not in ['unknown','unavailable','none',''] else none %}
          {% if wechsel and now().date() >= wechsel.date() %}
            {{ states('input_number.emlog_strom_preis_neu') | float(states('input_number.emlog_strom_preis_aktuell') | float(0)) }}
          {% else %}
            {{ states('input_number.emlog_strom_preis_aktuell') | float(0) }}
          {% endif %}

      - name: 'Emlog Strom Grundpreis pro Monat (effektiv)'
        unique_id: emlog_strom_grundpreis_monat_effektiv
        icon: mdi:calendar-month
        unit_of_measurement: 'EUR/Monat'
        state: >
          {% set dt = states('input_datetime.emlog_strom_tarifwechsel_ab') %}
          {% set wechsel = as_datetime(dt) if dt not in ['unknown','unavailable','none',''] else none %}
          {% if wechsel and now().date() >= wechsel.date() %}
            {{ states('input_number.emlog_strom_grundpreis_monat_neu') | float(states('input_number.emlog_strom_grundpreis_monat_aktuell') | float(0)) }}
          {% else %}
            {{ states('input_number.emlog_strom_grundpreis_monat_aktuell') | float(0) }}
          {% endif %}

      - name: 'Emlog Gas Arbeitspreis (effektiv)'
        unique_id: emlog_gas_preis_effektiv
        icon: mdi:tag
        unit_of_measurement: 'EUR/kWh'
        state: >
          {% set dt = states('input_datetime.emlog_gas_tarifwechsel_ab') %}
          {% set wechsel = as_datetime(dt) if dt not in ['unknown','unavailable','none',''] else none %}
          {% if wechsel and now().date() >= wechsel.date() %}
            {{ states('input_number.emlog_gas_preis_neu') | float(states('input_number.emlog_gas_preis_aktuell') | float(0)) }}
          {% else %}
            {{ states('input_number.emlog_gas_preis_aktuell') | float(0) }}
          {% endif %}

      - name: 'Emlog Gas Grundpreis pro Monat (effektiv)'
        unique_id: emlog_gas_grundpreis_monat_effektiv
        icon: mdi:calendar-month
        unit_of_measurement: 'EUR/Monat'
        state: >
          {% set dt = states('input_datetime.emlog_gas_tarifwechsel_ab') %}
          {% set wechsel = as_datetime(dt) if dt not in ['unknown','unavailable','none',''] else none %}
          {% if wechsel and now().date() >= wechsel.date() %}
            {{ states('input_number.emlog_gas_grundpreis_monat_neu') | float(states('input_number.emlog_gas_grundpreis_monat_aktuell') | float(0)) }}
          {% else %}
            {{ states('input_number.emlog_gas_grundpreis_monat_aktuell') | float(0) }}
          {% endif %}

      - name: 'Emlog Strom Kosten heute (EUR)'
        unique_id: emlog_strom_kosten_tag_eur
        icon: mdi:cash
        unit_of_measurement: 'EUR'
        device_class: monetary
        state_class: total
        state: >
          {% set kwh  = states('sensor.emlog_strom_verbrauch_tag_kwh') | float(0) %}
          {% set ap   = states('sensor.emlog_strom_preis_effektiv') | float(0) %}
          {% set gp_m = states('sensor.emlog_strom_grundpreis_monat_effektiv') | float(0) %}
          {% set next_month = (now().replace(day=28) + timedelta(days=4)).replace(day=1) %}
          {% set dim = (next_month - timedelta(days=1)).day | float(30) %}
          {{ (kwh * ap + (gp_m / dim)) | round(2) }}

      - name: 'Emlog Gas Kosten heute (EUR)'
        unique_id: emlog_gas_kosten_tag_eur
        icon: mdi:cash
        unit_of_measurement: 'EUR'
        device_class: monetary
        state_class: total
        state: >
          {% set kwh  = states('sensor.emlog_gas_verbrauch_tag_kwh') | float(0) %}
          {% set ap   = states('sensor.emlog_gas_preis_effektiv') | float(0) %}
          {% set gp_m = states('sensor.emlog_gas_grundpreis_monat_effektiv') | float(0) %}
          {% set next_month = (now().replace(day=28) + timedelta(days=4)).replace(day=1) %}
          {% set dim = (next_month - timedelta(days=1)).day | float(30) %}
          {{ (kwh * ap + (gp_m / dim)) | round(2) }}

      - name: 'Emlog Strom Kosten (Monat) (EUR)'
        unique_id: emlog_strom_kosten_monat_eur
        icon: mdi:cash-multiple
        unit_of_measurement: 'EUR'
        device_class: monetary
        state_class: total
        state: >
          {% set kwh = states('sensor.emlog_strom_verbrauch_monat_kwh') | float(0) %}
          {% set ap  = states('sensor.emlog_strom_preis_effektiv') | float(0) %}
          {% set gp  = states('sensor.emlog_strom_grundpreis_monat_effektiv') | float(0) %}
          {{ (kwh * ap + gp) | round(2) }}

      - name: 'Emlog Gas Kosten (Monat) (EUR)'
        unique_id: emlog_gas_kosten_monat_eur
        icon: mdi:cash-multiple
        unit_of_measurement: 'EUR'
        device_class: monetary
        state_class: total
        state: >
          {% set kwh = states('sensor.emlog_gas_verbrauch_monat_kwh') | float(0) %}
          {% set ap  = states('sensor.emlog_gas_preis_effektiv') | float(0) %}
          {% set gp  = states('sensor.emlog_gas_grundpreis_monat_effektiv') | float(0) %}
          {{ (kwh * ap + gp) | round(2) }}

      - name: 'Emlog Strom Kosten (Jahr) (EUR)'
        unique_id: emlog_strom_kosten_jahr_eur
        icon: mdi:cash-check
        unit_of_measurement: 'EUR'
        device_class: monetary
        state_class: total
        state: >
          {% set kwh = states('sensor.emlog_strom_verbrauch_jahr_kwh') | float(0) %}
          {% set ap  = states('sensor.emlog_strom_preis_effektiv') | float(0) %}
          {% set gp  = states('sensor.emlog_strom_grundpreis_monat_effektiv') | float(0) %}
          {{ (kwh * ap + (gp * 12)) | round(2) }}

      - name: 'Emlog Gas Kosten (Jahr) (EUR)'
        unique_id: emlog_gas_kosten_jahr_eur
        icon: mdi:cash-check
        unit_of_measurement: 'EUR'
        device_class: monetary
        state_class: total
        state: >
          {% set kwh = states('sensor.emlog_gas_verbrauch_jahr_kwh') | float(0) %}
          {% set ap  = states('sensor.emlog_gas_preis_effektiv') | float(0) %}
          {% set gp  = states('sensor.emlog_gas_grundpreis_monat_effektiv') | float(0) %}
          {{ (kwh * ap + (gp * 12)) | round(2) }}
